# Generated by Django 4.2.4 on 2024-03-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_video_alter_articles_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
