# Generated by Django 5.0.2 on 2024-03-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='anons',
            field=models.TextField(default='-', verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(upload_to='static\\img', verbose_name='Картинка'),
        ),
    ]
