# Generated by Django 5.0.2 on 2024-03-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_video_anons_alter_articles_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(upload_to='main\\static\\img', verbose_name='Картинка'),
        ),
    ]
