# Generated by Django 5.0.2 on 2024-03-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='place',
            field=models.TextField(default='none', verbose_name='Ссылка'),
        ),
    ]
